import dataclasses
from enum import Enum

class ErrorCodeEnum(str, Enum):
    MAPPING_ERROR = "MAPPING_ERROR"
    REFRESH_RELATIONS_ERROR = "REFRESH_RELATIONS_ERROR"
    DUPLICATE_ENTITY_ERROR = "DUPLICATE_ENTITY_ERROR"
    TRIGGER_WORKFLOW_ERROR = "TRIGGER_WORKFLOW_ERROR"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    BAD_CONFIG = "BAD_CONFIG"
    INTERNAL_ERROR = "INTERNAL_ERROR"
