"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .s3reference import S3Reference
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from epilot import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class InputDocument:
    r"""Input document"""
    s3ref: S3Reference = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('s3ref') }})
    


class OutputFormat(str, Enum):
    r"""Output format of the document"""
    PDF = 'pdf'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ConvertDocumentRequest:
    input_document: InputDocument = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('input_document') }})
    r"""Input document"""
    output_format: OutputFormat = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('output_format') }})
    r"""Output format of the document"""
    output_filename: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('output_filename'), 'exclude': lambda f: f is None }})
    r"""Filename of the output document (optional)"""
    

