"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from epilot_customer_portal.types import BaseModel
from typing import TypedDict


class Decision(str, Enum):
    r"""Acceptance decision"""
    ACCEPT = "accept"
    DECLINE = "decline"

class AcceptanceDecisionTypedDict(TypedDict):
    decision: Decision
    r"""Acceptance decision"""
    

class AcceptanceDecision(BaseModel):
    decision: Decision
    r"""Acceptance decision"""
    
