"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createuserrequest import CreateUserRequest, CreateUserRequestTypedDict
from .origin import Origin
from enum import Enum
from epilot_customer_portal.types import BaseModel
from epilot_customer_portal.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing import TypedDict
from typing_extensions import Annotated


class CreateUserRequest1TypedDict(TypedDict):
    create_user_request: CreateUserRequestTypedDict
    r"""Portal user payload"""
    origin: Origin
    r"""Origin of the portal"""
    

class CreateUserRequest1(BaseModel):
    create_user_request: Annotated[CreateUserRequest, FieldMetadata(request=RequestMetadata(media_type="application/json"))]
    r"""Portal user payload"""
    origin: Annotated[Origin, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))]
    r"""Origin of the portal"""
    

class CreateUserMessage(str, Enum):
    USER_CREATED_SUCCESSFULLY = "User created successfully"

class CreateUserResponseBodyTypedDict(TypedDict):
    r"""User created successfully."""
    
    message: CreateUserMessage
    

class CreateUserResponseBody(BaseModel):
    r"""User created successfully."""
    
    message: CreateUserMessage
    
