"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_customer_portal.types import BaseModel
from typing import List, TypedDict


class DeleteEntityFileTypedDict(TypedDict):
    entity_id: str
    r"""Entity ID"""
    entity_type: str
    r"""Entity type"""
    file_entity_ids: List[str]
    r"""Array of file entity IDs"""
    

class DeleteEntityFile(BaseModel):
    entity_id: str
    r"""Entity ID"""
    entity_type: str
    r"""Entity type"""
    file_entity_ids: List[str]
    r"""Array of file entity IDs"""
    
