"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .extensionauthblock import ExtensionAuthBlock, ExtensionAuthBlockTypedDict
from .extensionseamlesslink import ExtensionSeamlessLink, ExtensionSeamlessLinkTypedDict
from enum import Enum
from epilot_customer_portal.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Dict, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class DescriptionTypedDict(TypedDict):
    r"""Name of the extension."""

    en: str
    r"""Name of the extension in English."""


class Description(BaseModel):
    r"""Name of the extension."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, str] = pydantic.Field(init=False)

    en: str
    r"""Name of the extension in English."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class SchemasExtensionHookMeterReadingPlausibilityCheckCallTypedDict(TypedDict):
    body: Dict[str, str]
    r"""JSON body to use for authentication. Supports variable interpolation."""
    headers: Dict[str, str]
    r"""Headers to use. Supports variable interpolation."""
    url: str
    r"""URL to call. Supports variable interpolation."""


class SchemasExtensionHookMeterReadingPlausibilityCheckCall(BaseModel):
    body: Dict[str, str]
    r"""JSON body to use for authentication. Supports variable interpolation."""

    headers: Dict[str, str]
    r"""Headers to use. Supports variable interpolation."""

    url: str
    r"""URL to call. Supports variable interpolation."""


class SchemasExtensionHookMeterReadingPlausibilityCheckResolvedTypedDict(TypedDict):
    r"""Response to the call"""

    valid: NotRequired[str]
    r"""Indicate whether the meter reading is plausible"""


class SchemasExtensionHookMeterReadingPlausibilityCheckResolved(BaseModel):
    r"""Response to the call"""

    valid: Optional[str] = None
    r"""Indicate whether the meter reading is plausible"""


class SchemasExtensionHookMeterReadingPlausibilityCheckType(str, Enum):
    METER_READING_PLAUSIBILITY_CHECK = "meterReadingPlausibilityCheck"


class ExtensionHookMeterReadingPlausibilityCheckSchemasTypedDict(TypedDict):
    r"""Hook that checks the plausibility of meter readings before they are saved. This hook makes a POST call whenever a user is trying to save a meter reading. The expected response to the call is:
    - 200:
    If meter reading is plausible, the response should contain:
    - valid: true
    If meter reading is not plausible, the response should contain:
    - valid: false

    """

    call: SchemasExtensionHookMeterReadingPlausibilityCheckCallTypedDict
    resolved: SchemasExtensionHookMeterReadingPlausibilityCheckResolvedTypedDict
    r"""Response to the call"""
    type: SchemasExtensionHookMeterReadingPlausibilityCheckType
    auth: NotRequired[ExtensionAuthBlockTypedDict]
    id: NotRequired[str]
    r"""Identifier of the hook. Should not change between updates."""


class ExtensionHookMeterReadingPlausibilityCheckSchemas(BaseModel):
    r"""Hook that checks the plausibility of meter readings before they are saved. This hook makes a POST call whenever a user is trying to save a meter reading. The expected response to the call is:
    - 200:
    If meter reading is plausible, the response should contain:
    - valid: true
    If meter reading is not plausible, the response should contain:
    - valid: false

    """

    call: SchemasExtensionHookMeterReadingPlausibilityCheckCall

    resolved: SchemasExtensionHookMeterReadingPlausibilityCheckResolved
    r"""Response to the call"""

    type: SchemasExtensionHookMeterReadingPlausibilityCheckType

    auth: Optional[ExtensionAuthBlock] = None

    id: Optional[str] = None
    r"""Identifier of the hook. Should not change between updates."""


class SchemasExtensionHookCostDataRetrievalCallTypedDict(TypedDict):
    url: str
    r"""URL to call. Supports variable interpolation."""
    headers: NotRequired[Dict[str, str]]
    r"""Headers to use. Supports variable interpolation."""
    method: NotRequired[str]
    r"""HTTP method to use for the call"""
    params: NotRequired[Dict[str, str]]
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasExtensionHookCostDataRetrievalCall(BaseModel):
    url: str
    r"""URL to call. Supports variable interpolation."""

    headers: Optional[Dict[str, str]] = None
    r"""Headers to use. Supports variable interpolation."""

    method: Optional[str] = "GET"
    r"""HTTP method to use for the call"""

    params: Optional[Dict[str, str]] = None
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasResolvedTypedDict(TypedDict):
    data_path: NotRequired[str]
    r"""Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level."""


class SchemasResolved(BaseModel):
    data_path: Annotated[Optional[str], pydantic.Field(alias="dataPath")] = None
    r"""Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level."""


class SchemasExtensionHookCostDataRetrievalType(str, Enum):
    COST_DATA_RETRIEVAL = "costDataRetrieval"


class ExtensionHookCostDataRetrievalSchemasTypedDict(TypedDict):
    r"""Hook that will allow using the specified source as data for consumption visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
    - 200 with the time series data

    """

    call: SchemasExtensionHookCostDataRetrievalCallTypedDict
    type: SchemasExtensionHookCostDataRetrievalType
    auth: NotRequired[ExtensionAuthBlockTypedDict]
    id: NotRequired[str]
    r"""Identifier of the hook. Should not change between updates."""
    resolved: NotRequired[SchemasResolvedTypedDict]


class ExtensionHookCostDataRetrievalSchemas(BaseModel):
    r"""Hook that will allow using the specified source as data for consumption visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
    - 200 with the time series data

    """

    call: SchemasExtensionHookCostDataRetrievalCall

    type: SchemasExtensionHookCostDataRetrievalType

    auth: Optional[ExtensionAuthBlock] = None

    id: Optional[str] = None
    r"""Identifier of the hook. Should not change between updates."""

    resolved: Optional[SchemasResolved] = None


class CallTypedDict(TypedDict):
    url: str
    r"""URL to call. Supports variable interpolation."""
    headers: NotRequired[Dict[str, str]]
    r"""Headers to use. Supports variable interpolation."""
    method: NotRequired[str]
    r"""HTTP method to use for the call"""
    params: NotRequired[Dict[str, str]]
    r"""Parameters to append to the URL. Supports variable interpolation."""


class Call(BaseModel):
    url: str
    r"""URL to call. Supports variable interpolation."""

    headers: Optional[Dict[str, str]] = None
    r"""Headers to use. Supports variable interpolation."""

    method: Optional[str] = "GET"
    r"""HTTP method to use for the call"""

    params: Optional[Dict[str, str]] = None
    r"""Parameters to append to the URL. Supports variable interpolation."""


class ResolvedTypedDict(TypedDict):
    data_path: NotRequired[str]
    r"""Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level."""


class Resolved(BaseModel):
    data_path: Annotated[Optional[str], pydantic.Field(alias="dataPath")] = None
    r"""Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level."""


class Type(str, Enum):
    CONSUMPTION_DATA_RETRIEVAL = "consumptionDataRetrieval"


class SchemasTypedDict(TypedDict):
    r"""Hook that will allow using the specified source as data for consumption visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
    - 200 with the time series data

    """

    call: CallTypedDict
    type: Type
    auth: NotRequired[ExtensionAuthBlockTypedDict]
    id: NotRequired[str]
    r"""Identifier of the hook. Should not change between updates."""
    resolved: NotRequired[ResolvedTypedDict]


class Schemas(BaseModel):
    r"""Hook that will allow using the specified source as data for consumption visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
    - 200 with the time series data

    """

    call: Call

    type: Type

    auth: Optional[ExtensionAuthBlock] = None

    id: Optional[str] = None
    r"""Identifier of the hook. Should not change between updates."""

    resolved: Optional[Resolved] = None


class SchemasExtensionHookPriceDataRetrievalCallTypedDict(TypedDict):
    url: str
    r"""URL to call. Supports variable interpolation."""
    headers: NotRequired[Dict[str, str]]
    r"""Headers to use. Supports variable interpolation."""
    method: NotRequired[str]
    r"""HTTP method to use for the call"""
    params: NotRequired[Dict[str, str]]
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasExtensionHookPriceDataRetrievalCall(BaseModel):
    url: str
    r"""URL to call. Supports variable interpolation."""

    headers: Optional[Dict[str, str]] = None
    r"""Headers to use. Supports variable interpolation."""

    method: Optional[str] = "GET"
    r"""HTTP method to use for the call"""

    params: Optional[Dict[str, str]] = None
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasExtensionHookPriceDataRetrievalResolvedTypedDict(TypedDict):
    data_path: NotRequired[str]
    r"""Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level."""


class SchemasExtensionHookPriceDataRetrievalResolved(BaseModel):
    data_path: Annotated[Optional[str], pydantic.Field(alias="dataPath")] = None
    r"""Optional path to the data (array) in the response. If omitted, the data is assumed to be on the top level."""


class SchemasExtensionHookPriceDataRetrievalType(str, Enum):
    PRICE_DATA_RETRIEVAL = "priceDataRetrieval"


class ExtensionHookPriceDataRetrievalSchemasTypedDict(TypedDict):
    r"""Hook that will allow using the specified source as data for price visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
    - 200 with the time series data

    """

    call: SchemasExtensionHookPriceDataRetrievalCallTypedDict
    type: SchemasExtensionHookPriceDataRetrievalType
    auth: NotRequired[ExtensionAuthBlockTypedDict]
    id: NotRequired[str]
    r"""Identifier of the hook. Should not change between updates."""
    resolved: NotRequired[SchemasExtensionHookPriceDataRetrievalResolvedTypedDict]


class ExtensionHookPriceDataRetrievalSchemas(BaseModel):
    r"""Hook that will allow using the specified source as data for price visualizations. This hook is triggered to fetch the data. Format of the request and response has to follow the following specification: TBD. The expected response to the call is:
    - 200 with the time series data

    """

    call: SchemasExtensionHookPriceDataRetrievalCall

    type: SchemasExtensionHookPriceDataRetrievalType

    auth: Optional[ExtensionAuthBlock] = None

    id: Optional[str] = None
    r"""Identifier of the hook. Should not change between updates."""

    resolved: Optional[SchemasExtensionHookPriceDataRetrievalResolved] = None


class SchemasCallTypedDict(TypedDict):
    headers: Dict[str, str]
    r"""Headers to use. Supports variable interpolation."""
    url: str
    r"""URL to call. Supports variable interpolation."""
    params: NotRequired[Dict[str, str]]
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasCall(BaseModel):
    headers: Dict[str, str]
    r"""Headers to use. Supports variable interpolation."""

    url: str
    r"""URL to call. Supports variable interpolation."""

    params: Optional[Dict[str, str]] = None
    r"""Parameters to append to the URL. Supports variable interpolation."""


class ExplanationTypedDict(TypedDict):
    r"""Explanation of the hook."""

    en: str
    r"""Explanation of the functionality shown to the end user."""


class Explanation(BaseModel):
    r"""Explanation of the hook."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, str] = pydantic.Field(init=False)

    en: str
    r"""Explanation of the functionality shown to the end user."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class SchemasType(str, Enum):
    CONTRACT_IDENTIFICATION = "contractIdentification"


class ExtensionHookContractIdentificationSchemasTypedDict(TypedDict):
    r"""Hook that replaces the built-in contract identification for self-assignment. This hook makes a POST call whenever a user is trying to self-assign a contract to find the corresponding contract(s). The expected response to the call is:
    - 200 if found with either:
    - contract_id array
    - contact_id string
    - 404 if no contract is found
    If `contact_id` is provided in the response, Contracts are retrieved from this Contact. In that case, optionally, if you also specify `contact_relation_attribute`, the specified Contact attribute of the user performing the action will be modified to add the matched Contact.

    """

    call: SchemasCallTypedDict
    type: SchemasType
    auth: NotRequired[ExtensionAuthBlockTypedDict]
    contact_relation_attribute: NotRequired[str]
    r"""Name of the Contact attribute to update with the matched Contact ID. Must be a Contact relation attribute supporting multiple entities."""
    explanation: NotRequired[ExplanationTypedDict]
    r"""Explanation of the hook."""
    id: NotRequired[str]
    r"""Identifier of the hook. Should not change between updates."""


class ExtensionHookContractIdentificationSchemas(BaseModel):
    r"""Hook that replaces the built-in contract identification for self-assignment. This hook makes a POST call whenever a user is trying to self-assign a contract to find the corresponding contract(s). The expected response to the call is:
    - 200 if found with either:
    - contract_id array
    - contact_id string
    - 404 if no contract is found
    If `contact_id` is provided in the response, Contracts are retrieved from this Contact. In that case, optionally, if you also specify `contact_relation_attribute`, the specified Contact attribute of the user performing the action will be modified to add the matched Contact.

    """

    call: SchemasCall

    type: SchemasType

    auth: Optional[ExtensionAuthBlock] = None

    contact_relation_attribute: Optional[str] = None
    r"""Name of the Contact attribute to update with the matched Contact ID. Must be a Contact relation attribute supporting multiple entities."""

    explanation: Optional[Explanation] = None
    r"""Explanation of the hook."""

    id: Optional[str] = None
    r"""Identifier of the hook. Should not change between updates."""


class SchemasExtensionHookRegistrationIdentifiersCheckCallTypedDict(TypedDict):
    headers: Dict[str, str]
    r"""Headers to use. Supports variable interpolation."""
    result: str
    r"""Contact ID usually retrieved from the response body, e.g. `{{CallResponse.data.contact_id}}`. Supports variable interpolation."""
    url: str
    r"""URL to call. Supports variable interpolation."""
    params: NotRequired[Dict[str, str]]
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasExtensionHookRegistrationIdentifiersCheckCall(BaseModel):
    headers: Dict[str, str]
    r"""Headers to use. Supports variable interpolation."""

    result: str
    r"""Contact ID usually retrieved from the response body, e.g. `{{CallResponse.data.contact_id}}`. Supports variable interpolation."""

    url: str
    r"""URL to call. Supports variable interpolation."""

    params: Optional[Dict[str, str]] = None
    r"""Parameters to append to the URL. Supports variable interpolation."""


class SchemasExtensionHookRegistrationIdentifiersCheckType(str, Enum):
    REGISTRATION_IDENTIFIERS_CHECK = "registrationIdentifiersCheck"


class ExtensionHookRegistrationIdentifiersCheckSchemasTypedDict(TypedDict):
    r"""Hook that replaces the built-in registration identifiers check. This hook makes a POST call whenever a user is trying to register to find the corresponding contact. The expected response to the call is:
    - 200 with contact id if exactly one contact is found
    - 404 if no contact is found or more than contact is found

    """

    call: SchemasExtensionHookRegistrationIdentifiersCheckCallTypedDict
    type: SchemasExtensionHookRegistrationIdentifiersCheckType
    auth: NotRequired[ExtensionAuthBlockTypedDict]
    id: NotRequired[str]
    r"""Identifier of the hook. Should not change between updates."""


class ExtensionHookRegistrationIdentifiersCheckSchemas(BaseModel):
    r"""Hook that replaces the built-in registration identifiers check. This hook makes a POST call whenever a user is trying to register to find the corresponding contact. The expected response to the call is:
    - 200 with contact id if exactly one contact is found
    - 404 if no contact is found or more than contact is found

    """

    call: SchemasExtensionHookRegistrationIdentifiersCheckCall

    type: SchemasExtensionHookRegistrationIdentifiersCheckType

    auth: Optional[ExtensionAuthBlock] = None

    id: Optional[str] = None
    r"""Identifier of the hook. Should not change between updates."""


HooksTypedDict = TypeAliasType(
    "HooksTypedDict",
    Union[
        ExtensionHookRegistrationIdentifiersCheckSchemasTypedDict,
        ExtensionHookPriceDataRetrievalSchemasTypedDict,
        SchemasTypedDict,
        ExtensionHookCostDataRetrievalSchemasTypedDict,
        ExtensionHookMeterReadingPlausibilityCheckSchemasTypedDict,
        ExtensionHookContractIdentificationSchemasTypedDict,
    ],
)


Hooks = TypeAliasType(
    "Hooks",
    Union[
        ExtensionHookRegistrationIdentifiersCheckSchemas,
        ExtensionHookPriceDataRetrievalSchemas,
        Schemas,
        ExtensionHookCostDataRetrievalSchemas,
        ExtensionHookMeterReadingPlausibilityCheckSchemas,
        ExtensionHookContractIdentificationSchemas,
    ],
)


class NameTypedDict(TypedDict):
    r"""Name of the extension."""

    en: str
    r"""Name of the extension in English."""


class Name(BaseModel):
    r"""Name of the extension."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, str] = pydantic.Field(init=False)

    en: str
    r"""Name of the extension in English."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class ExtensionDescriptionTypedDict(TypedDict):
    r"""Description of the option."""

    en: str
    r"""Description of the option in English."""


class ExtensionDescription(BaseModel):
    r"""Description of the option."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, str] = pydantic.Field(init=False)

    en: str
    r"""Description of the option in English."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class ExtensionNameTypedDict(TypedDict):
    r"""Name of the option."""

    en: str
    r"""Name of the option in English."""


class ExtensionName(BaseModel):
    r"""Name of the option."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, str] = pydantic.Field(init=False)

    en: str
    r"""Name of the option in English."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]


class ExtensionType(str, Enum):
    r"""Type of the option."""

    TEXT = "text"
    SECRET = "secret"


class OptionsTypedDict(TypedDict):
    id: str
    r"""Identifier of the option. Should not change between updates."""
    name: ExtensionNameTypedDict
    r"""Name of the option."""
    type: ExtensionType
    r"""Type of the option."""
    default: NotRequired[str]
    r"""Default value of the option."""
    description: NotRequired[ExtensionDescriptionTypedDict]
    r"""Description of the option."""
    required: NotRequired[bool]
    r"""Indicate whether the option is required."""


class Options(BaseModel):
    id: str
    r"""Identifier of the option. Should not change between updates."""

    name: ExtensionName
    r"""Name of the option."""

    type: ExtensionType
    r"""Type of the option."""

    default: Optional[str] = None
    r"""Default value of the option."""

    description: Optional[ExtensionDescription] = None
    r"""Description of the option."""

    required: Optional[bool] = False
    r"""Indicate whether the option is required."""


class ExtensionTypedDict(TypedDict):
    description: DescriptionTypedDict
    r"""Name of the extension."""
    name: NameTypedDict
    r"""Name of the extension."""
    version: str
    r"""Version of the extension."""
    hooks: NotRequired[List[HooksTypedDict]]
    r"""Hooks that influence the behavior of Portal."""
    id: NotRequired[str]
    r"""Identifier of the extension. Should not change between updates."""
    links: NotRequired[List[ExtensionSeamlessLinkTypedDict]]
    r"""External links added to the portal."""
    options: NotRequired[List[OptionsTypedDict]]
    r"""Options available to the extension configurable by the portal administrator."""


class Extension(BaseModel):
    description: Description
    r"""Name of the extension."""

    name: Name
    r"""Name of the extension."""

    version: str
    r"""Version of the extension."""

    hooks: Optional[List[Hooks]] = None
    r"""Hooks that influence the behavior of Portal."""

    id: Optional[str] = None
    r"""Identifier of the extension. Should not change between updates."""

    links: Optional[List[ExtensionSeamlessLink]] = None
    r"""External links added to the portal."""

    options: Optional[List[Options]] = None
    r"""Options available to the extension configurable by the portal administrator."""
