"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from epilot_customer_portal.types import BaseModel
from epilot_customer_portal.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Interval(str, Enum):
    r"""Interval between consumption data points (e.g., PT15M for 15 minutes, PT1H for hourly). Not all intervals have to be supported."""

    PT15_M = "PT15M"
    PT1_H = "PT1H"
    P1_D = "P1D"
    P1_M = "P1M"


class GetConsumptionRequestTypedDict(TypedDict):
    from_: datetime
    r"""Start date for consumption data (ISO 8601 format)."""
    interval: Interval
    r"""Interval between consumption data points (e.g., PT15M for 15 minutes, PT1H for hourly). Not all intervals have to be supported."""
    to: datetime
    r"""End date for consumption data (ISO 8601 format)."""


class GetConsumptionRequest(BaseModel):
    from_: Annotated[
        datetime,
        pydantic.Field(alias="from"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
    r"""Start date for consumption data (ISO 8601 format)."""

    interval: Annotated[
        Interval, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Interval between consumption data points (e.g., PT15M for 15 minutes, PT1H for hourly). Not all intervals have to be supported."""

    to: Annotated[
        datetime, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""End date for consumption data (ISO 8601 format)."""


class ResponseBodyTypedDict(TypedDict):
    timestamp: datetime
    r"""ISO 8601 timestamp of the consumption record."""
    value: float
    r"""The consumption value."""
    type: NotRequired[str]
    r"""Optional type of the consumption, such as 'nt' (night time) or 'ht' (high time)."""


class ResponseBody(BaseModel):
    timestamp: datetime
    r"""ISO 8601 timestamp of the consumption record."""

    value: float
    r"""The consumption value."""

    type: Optional[str] = None
    r"""Optional type of the consumption, such as 'nt' (night time) or 'ht' (high time)."""
