"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_customer_portal.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class FileConfigTypedDict(TypedDict):
    shared_with_end_customer: NotRequired[bool]
    r"""Indicate whether the file is shared with the end customer"""
    

class FileConfig(BaseModel):
    shared_with_end_customer: Optional[bool] = None
    r"""Indicate whether the file is shared with the end customer"""
    

class EcpConfigTypedDict(TypedDict):
    file_config: NotRequired[FileConfigTypedDict]
    

class EcpConfig(BaseModel):
    file_config: Optional[FileConfig] = None
    

class TriggerPortalFlowTypedDict(TypedDict):
    activity_id: NotRequired[str]
    r"""Id of the activity"""
    ecp_config: NotRequired[EcpConfigTypedDict]
    

class TriggerPortalFlow(BaseModel):
    activity_id: Optional[str] = None
    r"""Id of the activity"""
    ecp_config: Optional[EcpConfig] = None
    
