"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_entity.types import BaseModel
import pydantic
from typing import TypedDict
from typing_extensions import Annotated


class S3ReferenceTypedDict(TypedDict):
    r"""The S3 bucket and key where the JSON file for import is located."""
    
    bucket: str
    r"""The name of the S3 bucket where the JSON file for import is stored."""
    key: str
    r"""The key or path to the JSON file within the S3 bucket."""
    

class S3Reference(BaseModel):
    r"""The S3 bucket and key where the JSON file for import is located."""
    
    bucket: str
    r"""The name of the S3 bucket where the JSON file for import is stored."""
    key: str
    r"""The key or path to the JSON file within the S3 bucket."""
    

class EntityImportParamsTypedDict(TypedDict):
    r"""The parameters for importing entities."""
    
    s3_reference: S3ReferenceTypedDict
    r"""The S3 bucket and key where the JSON file for import is located."""
    schema_: str
    r"""The schema of the entities being imported. This must match the schema of the entities on the platform."""
    

class EntityImportParams(BaseModel):
    r"""The parameters for importing entities."""
    
    s3_reference: Annotated[S3Reference, pydantic.Field(alias="S3Reference")]
    r"""The S3 bucket and key where the JSON file for import is located."""
    schema_: Annotated[str, pydantic.Field(alias="schema")]
    r"""The schema of the entities being imported. This must match the schema of the entities on the platform."""
    
