"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .relationentity import RelationEntity, RelationEntityTypedDict
from .relationitem import RelationItem, RelationItemTypedDict
from typing import Union
from typing_extensions import TypeAliasType


GetRelationsRespTypedDict = TypeAliasType(
    "GetRelationsRespTypedDict", Union[RelationItemTypedDict, RelationEntityTypedDict]
)


GetRelationsResp = TypeAliasType(
    "GetRelationsResp", Union[RelationItem, RelationEntity]
)
