"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_entity.types import BaseModel
from epilot_entity.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetRelationsV2RequestTypedDict(TypedDict):
    id: str
    r"""Entity id"""
    slug: str
    r"""Entity Type"""
    fields: NotRequired[List[str]]
    r"""List of entity fields to include in results"""
    from_: NotRequired[int]
    r"""Starting page number"""
    hydrate: NotRequired[bool]
    r"""When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place."""
    include_reverse: NotRequired[bool]
    r"""When true, includes reverse relations in response (other entities pointing to this entity)"""
    query: NotRequired[str]
    r"""Input to filter search results"""
    size: NotRequired[int]
    r"""Number of results to return per page"""
    

class GetRelationsV2Request(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    r"""Entity id"""
    slug: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    r"""Entity Type"""
    fields: Annotated[Optional[List[str]], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""List of entity fields to include in results"""
    from_: Annotated[Optional[int], pydantic.Field(alias="from"), FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = 0
    r"""Starting page number"""
    hydrate: Annotated[Optional[bool], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = False
    r"""When true, enables entity hydration to resolve nested $relation & $relation_ref references in-place."""
    include_reverse: Annotated[Optional[bool], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = False
    r"""When true, includes reverse relations in response (other entities pointing to this entity)"""
    query: Annotated[Optional[str], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Input to filter search results"""
    size: Annotated[Optional[int], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = 50
    r"""Number of results to return per page"""
    
