"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_entity.types import BaseModel
from epilot_entity.utils import FieldMetadata, PathParamMetadata
from typing import TypedDict
from typing_extensions import Annotated


class GetSchemaCapabilityRequestTypedDict(TypedDict):
    composite_id: str
    r"""Schema Slug and the Attribute ID"""
    

class GetSchemaCapabilityRequest(BaseModel):
    composite_id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    r"""Schema Slug and the Attribute ID"""
    
