"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_entity import utils
from epilot_entity.types import BaseModel
from epilot_entity.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, TypedDict


class GetTaxonomyClassificationRequestTypedDict(TypedDict):
    classification_slug: str
    r"""Taxonomy Classification slug"""


class GetTaxonomyClassificationRequest(BaseModel):
    classification_slug: Annotated[
        str,
        pydantic.Field(alias="classificationSlug"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Taxonomy Classification slug"""


class GetTaxonomyClassificationResponseBodyData(BaseModel):
    error: Optional[str] = None
    r"""The error message"""

    status: Optional[int] = None
    r"""The HTTP status code of the error"""


class GetTaxonomyClassificationResponseBody(Exception):
    r"""A generic error returned by the API"""

    data: GetTaxonomyClassificationResponseBodyData

    def __init__(self, data: GetTaxonomyClassificationResponseBodyData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, GetTaxonomyClassificationResponseBodyData)
