"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_entity.types import BaseModel
from epilot_entity.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import TypedDict
from typing_extensions import Annotated


class GetTaxonomyRequestTypedDict(TypedDict):
    taxonomy_slug: str
    r"""Taxonomy slug"""
    

class GetTaxonomyRequest(BaseModel):
    taxonomy_slug: Annotated[str, pydantic.Field(alias="taxonomySlug"), FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    r"""Taxonomy slug"""
    
