"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .entitysearchresults import EntitySearchResults, EntitySearchResultsTypedDict
from typing import Union
from typing_extensions import TypeAliasType


ListEntitiesResponseTypedDict = TypeAliasType(
    "ListEntitiesResponseTypedDict", Union[EntitySearchResultsTypedDict, str]
)


ListEntitiesResponse = TypeAliasType(
    "ListEntitiesResponse", Union[EntitySearchResults, str]
)
