"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from epilot_entity.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class RedirectEntityViewViewType(str, Enum):
    REDIRECT = "redirect"

class RedirectEntityViewTypedDict(TypedDict):
    route: NotRequired[str]
    view_type: NotRequired[RedirectEntityViewViewType]
    

class RedirectEntityView(BaseModel):
    route: Optional[str] = None
    view_type: Optional[RedirectEntityViewViewType] = None
    
