"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .powermetertype import PowerMeterType
from enum import Enum
from epilot_pricing.types import BaseModel
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class ComputePriceParamsPowerBillingPeriod(str, Enum):
    r"""The billing period (defaults to monthly)"""
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    EVERY_QUARTER = "every_quarter"
    EVERY_6_MONTHS = "every_6_months"
    YEARLY = "yearly"
    ONE_TIME = "one_time"

class ComputePriceParamsPowerConsumptionType(str, Enum):
    r"""The consumption type"""
    HOUSEHOLD = "household"
    HEATING_PUMP = "heating_pump"
    NIGHT_STORAGE_HEATING = "night_storage_heating"
    NIGHT_STORAGE_HEATING_COMMON_METER = "night_storage_heating_common_meter"

class ComputePriceParamsPowerType(str, Enum):
    r"""The type of energy to compute the price"""
    POWER = "power"

class ComputePriceParamsPowerTypedDict(TypedDict):
    r"""The compute price payload for power"""
    
    postal_code: str
    r"""The postal code to search for providers"""
    type: ComputePriceParamsPowerType
    r"""The type of energy to compute the price"""
    association_id: NotRequired[str]
    r"""The association id"""
    billing_period: NotRequired[ComputePriceParamsPowerBillingPeriod]
    r"""The billing period (defaults to monthly)"""
    consumption: NotRequired[float]
    r"""The monthly consumption to compute the price in kWh (to be deprecated in favor of consumption_HT)"""
    consumption_ht: NotRequired[float]
    r"""The monthly HT consumption to compute the price in kWh"""
    consumption_nt: NotRequired[float]
    r"""The monthly NT consumption to compute the price in kWh"""
    consumption_type: NotRequired[ComputePriceParamsPowerConsumptionType]
    r"""The consumption type"""
    meter_type: NotRequired[PowerMeterType]
    r"""The meter type for power"""
    

class ComputePriceParamsPower(BaseModel):
    r"""The compute price payload for power"""
    
    postal_code: str
    r"""The postal code to search for providers"""
    type: ComputePriceParamsPowerType
    r"""The type of energy to compute the price"""
    association_id: Optional[str] = None
    r"""The association id"""
    billing_period: Optional[ComputePriceParamsPowerBillingPeriod] = ComputePriceParamsPowerBillingPeriod.MONTHLY
    r"""The billing period (defaults to monthly)"""
    consumption: Optional[float] = None
    r"""The monthly consumption to compute the price in kWh (to be deprecated in favor of consumption_HT)"""
    consumption_ht: Annotated[Optional[float], pydantic.Field(alias="consumption_HT")] = None
    r"""The monthly HT consumption to compute the price in kWh"""
    consumption_nt: Annotated[Optional[float], pydantic.Field(alias="consumption_NT")] = None
    r"""The monthly NT consumption to compute the price in kWh"""
    consumption_type: Optional[ComputePriceParamsPowerConsumptionType] = ComputePriceParamsPowerConsumptionType.HOUSEHOLD
    r"""The consumption type"""
    meter_type: Optional[PowerMeterType] = None
    r"""The meter type for power"""
    
