"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SalesTax(str, Enum):
    NONTAXABLE = "nontaxable"
    REDUCED = "reduced"
    STANDARD = "standard"
