"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .recurrenceamount import RecurrenceAmount
from .taxamountbreakdown import TaxAmountBreakdown
from dataclasses_json import Undefined, dataclass_json
from epilot import utils
from typing import List, Optional, Union


@dataclasses.dataclass
class TotalDetailsRecurrences:
    pass


@dataclasses.dataclass
class TotalDetailsTaxes:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class Breakdown:
    r"""Breakdown of individual tax (and discount) amounts that add up to the totals."""
    recurrences: Optional[List[Union[RecurrenceAmount]]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('recurrences'), 'exclude': lambda f: f is None }})
    r"""The aggregated price items tax amount per rate."""
    taxes: Optional[List[Union[TaxAmountBreakdown]]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('taxes'), 'exclude': lambda f: f is None }})
    r"""The aggregated price items tax amount per rate."""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class TotalDetails:
    r"""The total details with tax (and discount) aggregated totals."""
    amount_shipping: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount_shipping'), 'exclude': lambda f: f is None }})
    r"""This is the sum of all the price item shipping amounts."""
    amount_tax: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('amount_tax'), 'exclude': lambda f: f is None }})
    r"""This is the sum of all the price item tax amounts."""
    breakdown: Optional[Breakdown] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('breakdown'), 'exclude': lambda f: f is None }})
    r"""Breakdown of individual tax (and discount) amounts that add up to the totals."""
    

