"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.components import documentgenerationv2request as components_documentgenerationv2request
from ...models.components import documentgenerationv2response as components_documentgenerationv2response
from ...models.components import httpmetadata as components_httpmetadata
from enum import Enum
from typing import Optional

class Mode(str, Enum):
    r"""Type of mode used for document generation flow:
    - partial_generation will have a intermediate step for users to validate and replace the variable values before generating the final document.
    - full_generation, goes through all the steps for the full generation of final document
    """
    PARTIAL_GENERATION = 'partial_generation'
    FULL_GENERATION = 'full_generation'


@dataclasses.dataclass
class GenerateDocumentV2Request:
    document_generation_v2_request: Optional[components_documentgenerationv2request.DocumentGenerationV2Request] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'application/json' }})
    job_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'job_id', 'style': 'form', 'explode': True }})
    r"""Job ID for tracking the status of document generation action"""
    mode: Optional[Mode] = dataclasses.field(default=Mode.FULL_GENERATION, metadata={'query_param': { 'field_name': 'mode', 'style': 'form', 'explode': True }})
    r"""Type of mode used for document generation flow:
    - partial_generation will have a intermediate step for users to validate and replace the variable values before generating the final document.
    - full_generation, goes through all the steps for the full generation of final document
    """
    



@dataclasses.dataclass
class GenerateDocumentV2Response:
    http_meta: components_httpmetadata.HTTPMetadata = dataclasses.field()
    document_generation_v2_response: Optional[components_documentgenerationv2response.DocumentGenerationV2Response] = dataclasses.field(default=None)
    r"""Generated document output"""
    

