"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import messagev2 as components_messagev2
from typing import Optional


@dataclasses.dataclass
class GetMessageV2Request:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    r"""Message ID"""
    



@dataclasses.dataclass
class GetMessageV2Response:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    message_v2: Optional[components_messagev2.MessageV2] = dataclasses.field(default=None)
    r"""Success"""
    

