"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SearchSortingEnum(str, Enum):
    A_Z = "A_Z"
    Z_A = "Z_A"
    DUE_DATE_ASC = "DUE_DATE_ASC"
    DUE_DATE_DESC = "DUE_DATE_DESC"
    TRIGGER_DATE_ASC = "TRIGGER_DATE_ASC"
    TRIGGER_DATE_DESC = "TRIGGER_DATE_DESC"
