"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .stepjourney import StepJourney, StepJourneyTypedDict
from epilot_workflows_execution.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class ECPDetailsTypedDict(TypedDict):
    r"""Details regarding ECP for the workflow step"""
    
    journey: NotRequired[StepJourneyTypedDict]
    label: NotRequired[str]
    

class ECPDetails(BaseModel):
    r"""Details regarding ECP for the workflow step"""
    
    journey: Optional[StepJourney] = None
    label: Optional[str] = None
    
