"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi import utils
from openapi.types import BaseModel
from typing import Optional


class ErrorRespErrorData(BaseModel):
    message: Optional[str] = None


class ErrorRespError(Exception):
    data: ErrorRespErrorData

    def __init__(self, data: ErrorRespErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ErrorRespErrorData)
