"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_internal_auth.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class GetOpenIDConfigurationResponseBodyTypedDict(TypedDict):
    r"""OpenID Configuration"""
    
    issuer: NotRequired[str]
    jwks_uri: NotRequired[str]
    

class GetOpenIDConfigurationResponseBody(BaseModel):
    r"""OpenID Configuration"""
    
    issuer: Optional[str] = None
    jwks_uri: Optional[str] = None
    
