"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_file.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class BaseEntityOwnerTypedDict(TypedDict):
    r"""The user / organization owning this entity.

    Note: Owner implicitly has access to the entity regardless of ACLs.

    """
    
    org_id: str
    user_id: NotRequired[str]
    

class BaseEntityOwner(BaseModel):
    r"""The user / organization owning this entity.

    Note: Owner implicitly has access to the entity regardless of ACLs.

    """
    
    org_id: str
    user_id: Optional[str] = None
    
