"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_file.types import BaseModel
from epilot_file.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class DeleteFileRequestTypedDict(TypedDict):
    id: str
    strict: NotRequired[bool]
    r"""When passed true, the response will contain only fields that match the schema, with non-matching fields included in `__additional`"""
    

class DeleteFileRequest(BaseModel):
    id: Annotated[str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))]
    strict: Annotated[Optional[bool], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = False
    r"""When passed true, the response will contain only fields that match the schema, with non-matching fields included in `__additional`"""
    
