"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .savecustomfilepayload import SaveCustomFilePayload, SaveCustomFilePayloadTypedDict
from .savefilefromsourceurlpayload import (
    SaveFileFromSourceURLPayload,
    SaveFileFromSourceURLPayloadTypedDict,
)
from .saves3filepayload import SaveS3FilePayload, SaveS3FilePayloadTypedDict
from typing import Union
from typing_extensions import TypeAliasType


SaveFilePayloadTypedDict = TypeAliasType(
    "SaveFilePayloadTypedDict",
    Union[
        SaveCustomFilePayloadTypedDict,
        SaveS3FilePayloadTypedDict,
        SaveFileFromSourceURLPayloadTypedDict,
    ],
)


SaveFilePayload = TypeAliasType(
    "SaveFilePayload",
    Union[SaveCustomFilePayload, SaveS3FilePayload, SaveFileFromSourceURLPayload],
)
