"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filerelationitem import FileRelationItem, FileRelationItemTypedDict
from .filetype import FileType
from enum import Enum
from epilot_file.types import BaseModel
import pydantic
from pydantic import ConfigDict
from typing import Any, Dict, List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class SaveCustomFilePayloadAccessControl(str, Enum):
    PRIVATE = "private"
    PUBLIC_READ = "public-read"


class SaveCustomFilePayloadTypedDict(TypedDict):
    id: NotRequired[str]
    manifest: NotRequired[List[str]]
    r"""Manifest ID used to create/update the entity"""
    purpose: NotRequired[List[str]]
    tags: NotRequired[List[str]]
    access_control: NotRequired[SaveCustomFilePayloadAccessControl]
    custom_download_url: NotRequired[str]
    r"""Custom external download url used for the file"""
    file_entity_id: NotRequired[str]
    r"""Deprecated, use _id instead"""
    filename: NotRequired[str]
    mime_type: NotRequired[str]
    r"""MIME type of the file"""
    relations: NotRequired[List[FileRelationItemTypedDict]]
    r"""List of entities to relate the file to"""
    type: NotRequired[FileType]


class SaveCustomFilePayload(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = None

    manifest: Annotated[Optional[List[str]], pydantic.Field(alias="_manifest")] = None
    r"""Manifest ID used to create/update the entity"""

    purpose: Annotated[Optional[List[str]], pydantic.Field(alias="_purpose")] = None

    tags: Annotated[Optional[List[str]], pydantic.Field(alias="_tags")] = None

    access_control: Optional[SaveCustomFilePayloadAccessControl] = (
        SaveCustomFilePayloadAccessControl.PRIVATE
    )

    custom_download_url: Optional[str] = None
    r"""Custom external download url used for the file"""

    file_entity_id: Annotated[
        Optional[str],
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ] = None
    r"""Deprecated, use _id instead"""

    filename: Optional[str] = None

    mime_type: Optional[str] = None
    r"""MIME type of the file"""

    relations: Optional[List[FileRelationItem]] = None
    r"""List of entities to relate the file to"""

    type: Optional[FileType] = None

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]
