"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .orgrole import OrgRole, OrgRoleTypedDict
from .partnerrole import PartnerRole, PartnerRoleTypedDict
from .portalrole import PortalRole, PortalRoleTypedDict
from .sharerole import ShareRole, ShareRoleTypedDict
from .userrole import UserRole, UserRoleTypedDict
from typing import Union


RoleTypedDict = Union[UserRoleTypedDict, ShareRoleTypedDict, PortalRoleTypedDict, OrgRoleTypedDict, PartnerRoleTypedDict]


Role = Union[UserRole, ShareRole, PortalRole, OrgRole, PartnerRole]

