"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accesstokentype import AccessTokenType
from epilot_access_token.types import BaseModel
from epilot_access_token.utils import FieldMetadata, QueryParamMetadata
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class ListAccessTokensRequestTypedDict(TypedDict):
    token_type: NotRequired[List[AccessTokenType]]
    r"""Filter by token types"""
    

class ListAccessTokensRequest(BaseModel):
    token_type: Annotated[Optional[List[AccessTokenType]], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Filter by token types"""
    
