"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_notification.types import BaseModel
from typing import Any, Dict, Optional, TypedDict
from typing_extensions import NotRequired


class ParamsTypedDict(TypedDict):
    id: NotRequired[str]
    slug: NotRequired[str]
    r"""URL-friendly identifier for the entity schema"""
    

class Params(BaseModel):
    id: Optional[str] = None
    slug: Optional[str] = None
    r"""URL-friendly identifier for the entity schema"""
    

class EntityOperationTypedDict(TypedDict):
    entity: str
    operation: NotRequired[str]
    params: NotRequired[ParamsTypedDict]
    payload: NotRequired[Dict[str, Any]]
    

class EntityOperation(BaseModel):
    entity: str
    operation: Optional[str] = None
    params: Optional[Params] = None
    payload: Optional[Dict[str, Any]] = None
    
