"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import contactexistsrequest as components_contactexistsrequest
from ...models.components import origin as components_origin
from dataclasses_json import Undefined, dataclass_json
from epilot import utils
from typing import Optional


@dataclasses.dataclass
class CheckContactExistsRequest:
    contact_exists_request: components_contactexistsrequest.ContactExistsRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""Request payload"""
    origin: components_origin.Origin = dataclasses.field(metadata={'query_param': { 'field_name': 'origin', 'style': 'form', 'explode': True }})
    r"""Origin of the portal"""
    



@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CheckContactExistsResponseBody:
    r"""Return result true|false if the contact with given identifiers exists."""
    exists: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('exists'), 'exclude': lambda f: f is None }})
    r"""Whether the contact exists with the given identifier values"""
    



@dataclasses.dataclass
class CheckContactExistsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    object: Optional[CheckContactExistsResponseBody] = dataclasses.field(default=None)
    r"""Return result true|false if the contact with given identifiers exists."""
    

