"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from dataclasses_json import Undefined, dataclass_json
from enum import Enum
from epilot import utils
from typing import Optional


@dataclasses.dataclass
class DeletePortalUserSecurity:
    portal_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' }})
    


class DeletePortalUserMessage(str, Enum):
    USER_SUCCESFULLY_DELETED = 'User Succesfully Deleted'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DeletePortalUserResponseBody:
    r"""Portal user deleted successfully."""
    data: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data'), 'exclude': lambda f: f is None }})
    r"""Entity ID"""
    message: Optional[DeletePortalUserMessage] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('message'), 'exclude': lambda f: f is None }})
    



@dataclasses.dataclass
class DeletePortalUserResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    object: Optional[DeletePortalUserResponseBody] = dataclasses.field(default=None)
    r"""Portal user deleted successfully."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

