"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .readingscope import ReadingScope
from epilot_message.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class ReadMessagePayloadTypedDict(TypedDict):
    scopes: List[ReadingScope]
    r"""The scopes to be used when marking an item as read or unread. The read status will be synced for all provided scopes."""


class ReadMessagePayload(BaseModel):
    scopes: List[ReadingScope]
    r"""The scopes to be used when marking an item as read or unread. The read status will be synced for all provided scopes."""
