"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .group import Group, GroupTypedDict
from epilot_user.types import BaseModel
from epilot_user.utils import FieldMetadata, QueryParamMetadata
from typing import List, Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class GetGroupsRequestTypedDict(TypedDict):
    hydrate: NotRequired[bool]
    r"""Pass it true when you want to hydrate the group with full user details"""
    limit: NotRequired[float]
    r"""Limit the results size"""
    offset: NotRequired[float]
    r"""Specify the offset"""
    query: NotRequired[str]
    r"""Query name to filter by"""
    

class GetGroupsRequest(BaseModel):
    hydrate: Annotated[Optional[bool], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Pass it true when you want to hydrate the group with full user details"""
    limit: Annotated[Optional[float], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Limit the results size"""
    offset: Annotated[Optional[float], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Specify the offset"""
    query: Annotated[Optional[str], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))] = None
    r"""Query name to filter by"""
    

class GetGroupsResponseBodyTypedDict(TypedDict):
    r"""List of groups"""
    
    groups: NotRequired[List[GroupTypedDict]]
    hits: NotRequired[float]
    

class GetGroupsResponseBody(BaseModel):
    r"""List of groups"""
    
    groups: Optional[List[Group]] = None
    hits: Optional[float] = None
    
