"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from epilot_user.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class OauthResponseType(str, Enum):
    CODE = "code"
    TOKEN = "token"

class LoginParametersTypedDict(TypedDict):
    cognito_oauth_domain: NotRequired[str]
    cognito_oauth_scopes: NotRequired[List[str]]
    cognito_region: NotRequired[str]
    cognito_user_pool_client_id: NotRequired[str]
    cognito_user_pool_id: NotRequired[str]
    oauth_response_type: NotRequired[OauthResponseType]
    organization_id: NotRequired[str]
    organization_name: NotRequired[str]
    organization_type: NotRequired[str]
    

class LoginParameters(BaseModel):
    cognito_oauth_domain: Optional[str] = None
    cognito_oauth_scopes: Optional[List[str]] = None
    cognito_region: Optional[str] = None
    cognito_user_pool_client_id: Optional[str] = None
    cognito_user_pool_id: Optional[str] = None
    oauth_response_type: Optional[OauthResponseType] = None
    organization_id: Optional[str] = None
    organization_name: Optional[str] = None
    organization_type: Optional[str] = None
    
