"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_user.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class UpdateGroupReqTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The name of the group. Could be a department or a team."""
    user_ids: NotRequired[List[str]]
    r"""The list of user ids in the group."""
    

class UpdateGroupReq(BaseModel):
    name: Optional[str] = None
    r"""The name of the group. Could be a department or a team."""
    user_ids: Optional[List[str]] = None
    r"""The list of user ids in the group."""
    
