"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from epilot_automation.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class Origin(str, Enum):
    TRIGGER = "trigger"
    ACTION = "action"


class ActionScheduleSourceTypedDict(TypedDict):
    r"""The source of the schedule_at timestamp that will be used to schedule the action"""

    attribute: str
    id: str
    r"""The id of the action or trigger"""
    origin: Origin
    schema_: str


class ActionScheduleSource(BaseModel):
    r"""The source of the schedule_at timestamp that will be used to schedule the action"""

    attribute: str

    id: str
    r"""The id of the action or trigger"""

    origin: Origin

    schema_: Annotated[str, pydantic.Field(alias="schema")]
