"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from epilot_automation.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class APISubmissionTriggerConfigurationTypedDict(TypedDict):
    source_id: NotRequired[str]
    

class APISubmissionTriggerConfiguration(BaseModel):
    source_id: Optional[str] = None
    

class APISubmissionTriggerType(str, Enum):
    API_SUBMISSION = "api_submission"

class APISubmissionTriggerTypedDict(TypedDict):
    configuration: APISubmissionTriggerConfigurationTypedDict
    type: APISubmissionTriggerType
    id: NotRequired[str]
    

class APISubmissionTrigger(BaseModel):
    configuration: APISubmissionTriggerConfiguration
    type: APISubmissionTriggerType
    id: Optional[str] = None
    
