"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .actioncondition import ActionCondition, ActionConditionTypedDict
from .anytrigger_input import AnyTriggerInput, AnyTriggerInputTypedDict
from .triggercondition import TriggerCondition, TriggerConditionTypedDict
from epilot_automation.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AutomationFlowInput1TypedDict(TypedDict):
    flow_name: str
    r"""A descriptive name for the Automation"""
    triggers: List[AnyTriggerInputTypedDict]
    conditions: NotRequired[List[ActionConditionTypedDict]]
    enabled: NotRequired[bool]
    r"""Whether the automation is enabled or not"""
    entity_schema: NotRequired[str]
    r"""The triggering entity schema"""
    runs: NotRequired[float]
    r"""Number of automation executions that ran"""
    system_flow: NotRequired[bool]
    r"""Determines if the flow is a system generated flow"""
    trigger_conditions: NotRequired[List[TriggerConditionTypedDict]]
    version: NotRequired[float]
    r"""Version of the flow"""


class AutomationFlowInput1(BaseModel):
    flow_name: str
    r"""A descriptive name for the Automation"""

    triggers: List[AnyTriggerInput]

    conditions: Optional[List[ActionCondition]] = None

    enabled: Optional[bool] = True
    r"""Whether the automation is enabled or not"""

    entity_schema: Optional[str] = None
    r"""The triggering entity schema"""

    runs: Optional[float] = None
    r"""Number of automation executions that ran"""

    system_flow: Optional[bool] = None
    r"""Determines if the flow is a system generated flow"""

    trigger_conditions: Optional[List[TriggerCondition]] = None

    version: Optional[float] = None
    r"""Version of the flow"""
