"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mappingattributemode import MappingAttributeMode
from epilot_automation.types import BaseModel
from typing import TypedDict
from typing_extensions import deprecated


@deprecated("warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.")
class CopyValueMapperTypedDict(TypedDict):
    mode: MappingAttributeMode
    r"""- copy_if_exists - it replaces the target attribute with the source value - append_if_exists - it currently replaces target attribute with array like values. Useful when you have multiple values to be added into one attribute. - set_value - it sets a value to a predefined value. Must be used together with value property.

    """
    source: str
    r"""JSON source path for the value to be extracted from the main entity. Eg: steps[1].['Product Info'].price

    """
    target: str
    r"""JSON like target path for the attribute. Eg. last_name"""
    

@deprecated("warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible.")
class CopyValueMapper(BaseModel):
    mode: MappingAttributeMode
    r"""- copy_if_exists - it replaces the target attribute with the source value - append_if_exists - it currently replaces target attribute with array like values. Useful when you have multiple values to be added into one attribute. - set_value - it sets a value to a predefined value. Must be used together with value property.

    """
    source: str
    r"""JSON source path for the value to be extracted from the main entity. Eg: steps[1].['Product Info'].price

    """
    target: str
    r"""JSON like target path for the attribute. Eg. last_name"""
    
