"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .anythingbutcondition import AnythingButCondition, AnythingButConditionTypedDict
from .equalsignorecasecondition import (
    EqualsIgnoreCaseCondition,
    EqualsIgnoreCaseConditionTypedDict,
)
from .existscondition import ExistsCondition, ExistsConditionTypedDict
from .numericcondition import NumericCondition, NumericConditionTypedDict
from .orcondition import OrCondition, OrConditionTypedDict
from .prefixcondition import PrefixCondition, PrefixConditionTypedDict
from .suffixcondition import SuffixCondition, SuffixConditionTypedDict
from .wildcardcondition import WildcardCondition, WildcardConditionTypedDict
from typing import Dict, List, Union
from typing_extensions import TypeAliasType


TwoTypedDict = TypeAliasType(
    "TwoTypedDict",
    Union[
        EqualsIgnoreCaseConditionTypedDict,
        AnythingButConditionTypedDict,
        NumericConditionTypedDict,
        ExistsConditionTypedDict,
        PrefixConditionTypedDict,
        SuffixConditionTypedDict,
        WildcardConditionTypedDict,
        str,
    ],
)


Two = TypeAliasType(
    "Two",
    Union[
        EqualsIgnoreCaseCondition,
        AnythingButCondition,
        NumericCondition,
        ExistsCondition,
        PrefixCondition,
        SuffixCondition,
        WildcardCondition,
        str,
    ],
)


DiffAddedTypedDict = TypeAliasType(
    "DiffAddedTypedDict", Union[OrConditionTypedDict, Dict[str, List[TwoTypedDict]]]
)


DiffAdded = TypeAliasType("DiffAdded", Union[OrCondition, Dict[str, List[Two]]])
