"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from epilot_automation.types import BaseModel
from typing import Optional, TypedDict
from typing_extensions import NotRequired


class FrontendSubmitTriggerConfigurationTypedDict(TypedDict):
    source_id: NotRequired[str]
    

class FrontendSubmitTriggerConfiguration(BaseModel):
    source_id: Optional[str] = None
    

class FrontendSubmitTriggerType(str, Enum):
    FRONTEND_SUBMISSION = "frontend_submission"

class FrontendSubmitTriggerTypedDict(TypedDict):
    configuration: FrontendSubmitTriggerConfigurationTypedDict
    type: FrontendSubmitTriggerType
    id: NotRequired[str]
    

class FrontendSubmitTrigger(BaseModel):
    configuration: FrontendSubmitTriggerConfiguration
    type: FrontendSubmitTriggerType
    id: Optional[str] = None
    
