"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filterconditiononevent import (
    FilterConditionOnEvent,
    FilterConditionOnEventTypedDict,
)
from epilot_automation.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OrCondition21TypedDict(TypedDict):
    dollar_or: NotRequired[List[FilterConditionOnEventTypedDict]]


class OrCondition21(BaseModel):
    dollar_or: Annotated[
        Optional[List[FilterConditionOnEvent]], pydantic.Field(alias="$or")
    ] = None
