"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_automation.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PrefixConditionTypedDict(TypedDict):
    prefix: NotRequired[str]


class PrefixCondition(BaseModel):
    prefix: Optional[str] = None
