"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .comparison import Comparison
from epilot_automation.types import BaseModel
from typing import List, Optional, TypedDict, Union
from typing_extensions import NotRequired


ValueTypedDict = Union[str, float, List[str], List[float]]


Value = Union[str, float, List[str], List[float]]


class TriggerConditionTypedDict(TypedDict):
    comparison: Comparison
    source: str
    value: NotRequired[ValueTypedDict]
    

class TriggerCondition(BaseModel):
    comparison: Comparison
    source: str
    value: Optional[Value] = None
    
