"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from epilot_automation.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class TriggerWebhookConfigTypedDict(TypedDict):
    entity_sources: NotRequired[List[str]]
    sync: NotRequired[bool]
    r"""Whether to wait for the request to finish before continuing automation execution"""
    target_webhook_id: NotRequired[str]
    

class TriggerWebhookConfig(BaseModel):
    entity_sources: Optional[List[str]] = None
    sync: Optional[bool] = False
    r"""Whether to wait for the request to finish before continuing automation execution"""
    target_webhook_id: Optional[str] = None
    
