"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .assignableecpplaceholder import (
    AssignableEcpPlaceholder,
    AssignableEcpPlaceholderTypedDict,
)
from .assignablegroup import AssignableGroup, AssignableGroupTypedDict
from .assignableorganization import (
    AssignableOrganization,
    AssignableOrganizationTypedDict,
)
from .assignablepartneruser import AssignablePartnerUser, AssignablePartnerUserTypedDict
from .assignableuser import AssignableUser, AssignableUserTypedDict
from typing import Union
from typing_extensions import TypeAliasType


AssignableTypedDict = TypeAliasType(
    "AssignableTypedDict",
    Union[
        AssignableUserTypedDict,
        AssignableGroupTypedDict,
        AssignablePartnerUserTypedDict,
        AssignableEcpPlaceholderTypedDict,
        AssignableOrganizationTypedDict,
    ],
)


Assignable = TypeAliasType(
    "Assignable",
    Union[
        AssignableUser,
        AssignableGroup,
        AssignablePartnerUser,
        AssignableEcpPlaceholder,
        AssignableOrganization,
    ],
)
