"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EntitySlug(str, Enum):
    r"""URL-friendly identifier for the entity schema"""
    CONTACT = 'contact'
    CONTRACT = 'contract'
    FILE = 'file'
    ORDER = 'order'
    OPPORTUNITY = 'opportunity'
    PRODUCT = 'product'
    PRICE = 'price'
    METER = 'meter'
    METER_COUNTER = 'meter_counter'
