"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OriginEnum(str, Enum):
    r"""Origin of the portal"""
    END_CUSTOMER_PORTAL = "END_CUSTOMER_PORTAL"
    INSTALLER_PORTAL = "INSTALLER_PORTAL"
